### ISSUE TITLE
Myprofile

### ISSUE THREAD

**Issue by eerison** [2KAbhishek/resume.md#1]
### Description of the bug

Hello @2KAbhishek   :) , in case you have sometime.

give a try in [myprofile project](https://github.com/shield-wall/myprofile), you can generate your resume just using yaml syntax in discussion section in github.

in the end, you will generate something like this: https://github.com/shield-wall/myprofile/discussions/723

### Steps To Reproduce

.

**Comment by 2KAbhishek** [comment]
Thanks for sharing, I'll take a look
